### PR TITLE
Mobile-friendly competiiton pages

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Various changes to enable use of these pages on smaller screens. Suggest review by commit.

Nav adjusts a bit like the docs sidebar does:
image

Team/match choosers get dynamic wrapping:
Screen Shot 2024-03-28 at 18 16 44
Screen Shot 2024-03-28 at 18 17 26

Youtube embed on the homepage is responsive:
Screen Shot 2024-03-28 at 18 18 58

The rest of the homepage is left as-is. While we probably could do more with the various bits, that's likely to need deeper surgery than I have time for right now.

Builds on https://github.com/srobo/competition-website/pull/52 for ease.

### CODE REVIEW

**Comment by raccube** [comment]
Oops, didn't meant to close this.

**Comment by raccube** [comment]
Oops, didn't meant to close this.

**Comment by PeterJCLaw** [comment]
> The rest of the homepage is left as-is. While we probably could do more with the various bits, that's likely to need deeper surgery than I have time for right now.

I've had a quick go at this. I think there's still a lot more which could be done (mostly by reworking to use e.g: flexbox rather than floats & absolute position munging), but that's definitely more than I have time for.

**Review by raccube — APPROVED** [review]
image
image

**Pull request merged**
