### PR TITLE
Make the competition website homepage more like the main website homepage

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This copies over the hero block at the top of the page and moves to using panels for the content. I think there's a lot more we could do here, though ideally it needs input from a designer to work out a better layout. This at least gets a little more information about who we are onto the page.

Please focus review on the layout/design, rather than the code.

This contributes towards https://github.com/srobo/tasks/issues/796.

**Current**
image

**Proposed**
image

**Reference**
image

### CODE REVIEW

**Review by antoinepetty — APPROVED** [review]
Looks good! We should add the "about us" content from the regular homepage below but that can be handled separately

**Comment by PeterJCLaw** [comment]
> Looks good! We should add the "about us" content from the regular homepage below but that can be handled separately

Ah, do you mean essentially having the competition live parts essentially being an insert into the main homepage (rather than replacing it entirely)?

**Comment by antoinepetty** [comment]
Yeah that was my vision. We could do it a different way if there's a better one though - the goal is to keep the "about us" information available for potential sponsors/press etc

**Comment by PeterJCLaw** [comment]
Full screenshot:
image

**Comment by PeterJCLaw** [comment]
Unfortunately this now entails a lot of duplication between this repo and the main website. I've some ideas on how to improve that (mostly that we build a JS library which does most of this and then inject that into the real homepage, rather than this duplication), but that'll have to wait for another year.

**Comment by antoinepetty** [comment]
Thanks Peter! This is a lot better. 

Are we able to fix the left alignment of the Match Schedule heading and the competition navigation links?

**Review by antoinepetty — APPROVED** [review]
My local copy is borked so can't double check but I trust your css

**Pull request merged**
