### PR TITLE
Enable user tracking

### PR DESCRIPTION
**Pull request by RealOrangeOne**
This provides us with analytics on the site.

This will inflate page views on the homepage, as the comp site overrides it, but that should be fine

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
> This will inflate page views on the homepage, as the comp site overrides it, but that should be fine

Why would this inflate views? Surely the tracking records the current url, at which point it doesn't matter which repo actually served the tracking code?

**Comment by PeterJCLaw** [comment]
Aside: should we have this in the docs too?

**Comment by RealOrangeOne** [comment]
> Why would this inflate views? Surely the tracking records the current url

Because exactly that. When in comp mode, `/` isn't actually the homepage.

> should we have this in the docs too

Already is

**Comment by PeterJCLaw** [comment]
> > Why would this inflate views? Surely the tracking records the current url
> 
> Because exactly that. When in comp mode, `/` isn't actually the homepage.

I guess that's a matter of perspective. It's a page which shows different content, but at those times it _is_ the homepage.

> > should we have this in the docs too
> 
> Already is

Huh. I grepped for `user_tracking` and didn't get any hits.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne what sort of review are you looking for here?

**Comment by RealOrangeOne** [comment]
normal? That the diff does what the PR says it should

**Comment by PeterJCLaw** [comment]
> normal? That the diff does what the PR says it should

Given that this is changing config I wasn't sure if this was more "is this a change we want to make" rather than "does this have the described effect".

**Review by PeterJCLaw — APPROVED** [review]

**Pull request merged**
